sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t idenkov/travis -f Dockerfile.dev .

script:
  - docker run -e CI=true idenkov/travis npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "travis"
  env: "Travis-env"
  bucket_name: "elasticbeanstalk-eu-central-1-847761946520"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"